users:
    - default
    - name: terraform
      gecos: terraform
      primary_group: hashicorp
      sudo: ALL=(ALL) NOPASSWD:ALL
      groups: users, admin
      ssh_import_id:
      lock_passwd: false
      ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDtcQJEQscsfycFKZmItK5SZogna9IAnk8uBG63Aal4L+9sowe5ZX9pLwu+j8CcL8UAROQBkJjbK7W9XmOIp0AMQaImT5gdCq1mQf2D8DqEPgm5aHwZMFvJBG4c3uCgq1tRw8cGe/U1PxqhiNXjCauJEoJYzKJEGsgoBiwtMBzx91RluDm69Eo0x2Rngro8q57s8h1ya8KJjWDOUO07dbX/R6EvbP8ye2fd/+KBCzciy7g4Eg27YslFCD0KI1jHpX0N91+9UskXcMyNbD35oX+HjxqvryCXAvoWG23is9B45bwE4/LhT0Gz6inqlirO3QW8TwwOReCOStzSK3sQrzRg5TUWZSEX5+/fZS3zFUE+jA/1moYNspSWtWsY+GeFefTmbIsycX8itKeYPysaGjI9q0aBrgnRswLHmnsbjoeQjCPC6h9gqZzFyVKuT4NQQ7kP4emREpQ8+Kjf3DdwZOtX/8RmWKwMX5QO0xoAvy+cQ5TXAZaQW5HlIyHfFp29ZQ5KjqnDY4niEYxYav/G1XW+5unnHsAHNxn4CfdnMyiGpjYDPdkYcxLrUu0jRIJskiw3UaUyv1r+qk0jkuwDQlhD/3EtY+iVaCIBUx4efxVHLDUT3pqVlh+mZ/pGQUzTYRs7PAvCdfS86eJYR4WRtybX/cD83HxQzo2UFUpX39ZeKw== derrick@dlee.dev

apt:
    sources:
        hashicorp.list:
            source: deb [arch=amd64] https://apt.releases.hashicorp.com $RELEASE main
            keyid: E8A032E094D8EB4EA189D270DA418C88A3219F7B

        docker.list:
            source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
            keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
    - curl
    - wget
    - git
    - vim
    - apt-transport-https
    - ca-certificates
    - gnupg
    - lsb-release
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - consul
    - nomad
    - vault
    # Forward DNS for Consul Service Discovery
    - dnsmasq

runcmd:
    # Start dnsmask service and enable it to start at every reboot
    - pidof systemd && systemctl restart dnsmasq.service || service dnsmasq restart
    - pidof systemd && systemctl enable  dnsmasq.service || chkconfig dnsmasq on

write_files:
    - path: /etc/consul.d/consul.hcl
      content: |
          datacenter = "nbg1"
          data_dir = "/opt/consul"
          encrypt = ""
          ca_file = "/etc/consul.d/consul-agent-ca.pem"
          cert_file = "/etc/consul.d/nbg1-server-consul-0.pem"
          key_file = "/etc/consul.d/nbg1-server-consul-0-key.pem"
          verify_incoming = true
          verify_outgoing = true
          verify_server_hostname = true
          retry_join = ["10.0.1.1"]
          acl = {
            enabled = true
            default_policy = "allow"
            enable_token_persistence = true
          }
    - path: /etc/nomad.d/nomad.hcl
      content: |
          datacenter = "nbg1"
          data_dir = "/opt/nomad/data"
          bind_addr = "10.0.1.1"

          consul {
            address = "127.0.0.1:8500"
            tags = ["traefik.enable=true"]
          }
    - path: /etc/dnsmasq.d/10-consul
      content: |
          # https://learn.hashicorp.com/tutorials/consul/dns-forwarding#dnsmasq-setup
          # Enable forward lookup of the 'consul' domain:
          server=/consul/127.0.0.1#8600
          server=1.1.1.1
          server=1.0.0.1
