version: "3.8"
services:
    postgres:
        ports:
            - "5432:5432"
    twilight-http-proxy:
        ports:
            - "3001:80"
        environment:
            - RUST_LOG=twilight_http_proxy=trace
    twilight-dispatch:
        environment:
            - RUST_LOG=info
            - BOT_TOKEN=$DISCORD_TOKEN
            - SHARDS_START=0
            - SHARDS_END=0
            - SHARDS_TOTAL=1
            - SHARDS_CONCURRENCY=1
            - SHARDS_WAIT=6
            - CLUSTERS=1
            - DEFAULT_QUEUE=true
            - RESUME=true
            - INTENTS=13831
            - LARGE_THRESHOLD=250
            - STATUS=online
            - ACTIVITY_TYPE=0
            - ACTIVITY_NAME=meow
            # Discord channel logs
            - LOG_CHANNEL=749822555019280434
            - LOG_GUILD_CHANNEL=749822555019280434
            - STATE_ENABLED=true
            - STATE_MEMBER=true
            - STATE_MEMBER_TTL=60000
            - STATE_MESSAGE=true
            - STATE_MESSAGE_TTL=60000
            - STATE_PRESENCE=false
            - RABBIT_HOST=rabbitmq
            - RABBIT_PORT=5672
            - RABBIT_USERNAME=guest
            - RABBIT_PASSWORD=guest
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PROMETHEUS_HOST=127.0.0.1
            - PROMETHEUS_PORT=8005
    sushii:
        build:
            dockerfile: ./sushii-2/Dockerfile
            context: .
    sushii-feeds:
        build:
            dockerfile: ./sushii-feeds/Dockerfile
            context: .
        ports:
            - "50051:50051"
    redis:
        ports:
            - "6379:6379"
    rabbitmq:
        ports:
            - "5672:5672"
            - "15672:15672"
    postgres_exporter:
        ports:
            - "9187:9187"
