version: "3.8"
services:
    postgres:
        ports:
            - "5432:5432"
    twilight-http-proxy:
        ports:
            - "3001:80"
        environment:
            - RUST_LOG=twilight_http_proxy=trace
    sushii:
        build:
            dockerfile: ./sushii-2/Dockerfile
            context: .
    sushii-feeds:
        build:
            dockerfile: ./sushii-feeds/Dockerfile
            context: .
        ports:
            - "50051:50051"
    redis:
        ports:
            - "6379:6379"
    rabbitmq:
        ports:
            - "5672:5672"
            - "15672:15672"
    postgres_exporter:
        ports:
            - "9187:9187"
