version: "3.8"
services:
    postgres:
        ports:
            - "5432:5432"
    twilight-http-proxy:
        ports:
            - "3000:80"
    sushii:
        build:
            dockerfile: ./sushii-2/Dockerfile
            context: .
    sushii-api:
        build:
            dockerfile: ./sushii-api/Dockerfile
            context: .
        ports:
            - "8080:8080"
    sushii-api:
        build:
            dockerfile: ./sushii-feeds/Dockerfile
            context: .
        ports:
            - "50051:50051"
    postgres_exporter:
        ports:
            - "9187:9187"
