INSERT INTO guild_configs (
    id,
    prefix,
    join_msg,
    join_msg_enabled,
    join_react,
    leave_msg,
    leave_msg_enabled,
    msg_channel,
    role_channel,
    role_config,
    role_enabled,
    invite_guard,
    log_msg,
    log_msg_enabled,
    log_mod,
    log_mod_enabled,
    log_member,
    log_member_enabled,
    mute_role,
    mute_duration,
    warn_dm_text,
    warn_dm_enabled,
    mute_dm_text,
    mute_dm_enabled,
    max_mention,
    disabled_channels
  )
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26
  ) ON CONFLICT (id) DO
UPDATE
SET -- id = $1, Don't need to update ID 
  prefix = $2,
  join_msg = $3,
  join_msg_enabled = $4,
  join_react = $5,
  leave_msg = $6,
  leave_msg_enabled = $7,
  msg_channel = $8,
  role_channel = $9,
  role_config = $10,
  role_enabled = $11,
  invite_guard = $12,
  log_msg = $13,
  log_msg_enabled = $14,
  log_mod = $15,
  log_mod_enabled = $16,
  log_member = $17,
  log_member_enabled = $18,
  mute_role = $19,
  mute_duration = $20,
  warn_dm_text = $21,
  warn_dm_enabled = $22,
  mute_dm_text = $23,
  mute_dm_enabled = $24,
  max_mention = $25,
  disabled_channels = $26
