INSERT INTO guild_configs (
    id,
    name,
    prefix,
    join_msg,
    join_msg_enabled,
    join_react,
    leave_msg,
    leave_msg_enabled,
    msg_channel,
    role_channel,
    role_config,
    role_enabled,
    invite_guard,
    log_msg,
    log_msg_enabled,
    log_mod,
    log_mod_enabled,
    log_member,
    log_member_enabled,
    mute_role,
    mute_duration,
    warn_dm_text,
    warn_dm_enabled,
    mute_dm_text,
    mute_dm_enabled,
    max_mention,
    disabled_channels
  )
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27
  ) ON CONFLICT (id) DO
UPDATE
SET -- id = $1, Don't need to update ID 
  name = $2,
  prefix = $3,
  join_msg = $4,
  join_msg_enabled = $5,
  join_react = $6,
  leave_msg = $7,
  leave_msg_enabled = $8,
  msg_channel = $9,
  role_channel = $10,
  role_config = $11,
  role_enabled = $12,
  invite_guard = $13,
  log_msg = $14,
  log_msg_enabled = $15,
  log_mod = $16,
  log_mod_enabled = $17,
  log_member = $18,
  log_member_enabled = $19,
  mute_role = $20,
  mute_duration = $21,
  warn_dm_text = $22,
  warn_dm_enabled = $23,
  mute_dm_text = $24,
  mute_dm_enabled = $25,
  max_mention = $26,
  disabled_channels = $27