---
- name: Install docker on clients
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - docker

- name: Install Consul
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - consul

- name: Install Nomad
  hosts: all
  become: yes
  gather_facts: no
  vars:
    nomad_version: 1.2.6
  roles:
    - nomad
