---
- name: Install cloud-init
  become: yes
  package:
    name: cloud-init
    state: present

- name: Install dnsmaq
  become: yes
  package:
    name: dnsmasq
    state: present

- name: Add dnsmasq config for consul
  become: yes
  copy:
    src: 10-consul
    dest: /etc/dnsmasq.d/10-consul
    owner: root
    mode: 0644

- name: Disable systemd-resolved
  become: yes
  systemd:
    state: stopped
    enabled: no
    name: systemd-resolved
    daemon_reload: yes

- name: Start dnsmasq service
  become: yes
  systemd:
    state: restarted
    enabled: yes
    name: dnsmasq
    daemon_reload: yes

- name: Forward system DNS requests to dnsmasq
  become: yes
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
