---
- name: Install unzip
  become: yes
  package:
    name: unzip
    state: present

- name: Get consul binary
  become: no
  get_url:
    url: https://releases.hashicorp.com/consul/1.11.4/consul_1.11.4_linux_amd64.zip
    dest: ~/consul.zip

- name: Extract consul
  become: yes
  shell: unzip ~/consul.zip -d /usr/local/bin/ && chmod +x /usr/local/bin/consul && rm ~/*.zip
  args:
    creates: /usr/local/bin/consul
