---
- name: install docker deps
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - python3-pip

- name: add docker repo apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repo to apt
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present

- name: install docker
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
